### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by UmerZia** [blase147/blase-tv#59]
## Hello 👋, In the issue:
- We assign roles to each member.
- **Note:** Total group members: **3**
- Student A (@UmerZia) Student B (@demix007) Student C (@blase147)
- **Project Link: https://github.com/blase147/blase-tv**

**Comment by omar-muhamad** [comment]
# Invalid ❌

Hi Team,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] You didn't add a link to your GitHub project in your issue description. Please fix that. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by christianbiring1** [comment]
Hi @blase147 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# REQUEST CHANGES :recycle: 

## Highlights
- [ ] All members are listed
- [ ] The tasks are distributed equally :+1: 

## Required Changes ♻️
- [ ] Kindly make sure each task has been assigned to a member. the photo of the member is supposed to be aside the task as it is in this image bellow :point_down: 
![Screenshot from 2022-11-01 15-34-28](https://user-images.githubusercontent.com/97100091/199246909-eda98e00-849f-403e-ae43-f1fac2332fd4.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by UmerZia** [comment]
We assigned tasks to the respective student. ✔️

**Comment by sajid-munawar** [comment]
Hi Team, 

Great job for making the necessary changes recommended by the previous reviewer. However, there's always room for improvement.
Kindly consider my OPTIONAL comments

## Optional suggestions
_Please keep in mind that you, for best practices and following the project requirements and the design templates closely kindly consider these aspects as outlined in the below comments._

- [ Optional] Number of cards on the board should be equal to 20. it seems that you have not deleted extra cards. Kindly endeavor to improve this aspect

**_Kindly notice that these are required changes, I'm sorry they didn't show up in the earlier review._**


<br>
Your project is complete! Congratulations! 🥂There is nothing else to say other than... it's time to merge it 👍.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
